@extends('layouts.form.single_form_legacy')

@section('htmlTitle', 'Deposit Pokemon')
@section('form_title', 'Deposit Pokemon')
@section('submit_string', 'Deposit Pokemon')

@section('header')
    @vite([
        'resources/css/components/form/components/file_uploader.css',
        'resources/ts/modules/pksanc/deposit.ts',
    ])
@stop

@section('onload_functions', 'init()')

@section('form_content')
    {{--| info blurb |--}}
    <div class="text-center">
        <div>Import a set of pokemon from a save file into PKSanc.</div>
        <p>
            Save files must be uploaded in CSV form generated by
            <a href="https://github.com/lati111/PKSaveExtract" class="interactive">PKSaveExtract</a> in PKSanc format
        </p>
    </div>


    <div class="flex flex-col justify-center items-center gap-3">
        {{--| save name field |--}}
        <x-form.input-wrapper label_text="Save file name" cls="large_input h-8">
            <input type="text" name="name" class="default_input_height underlined" placeholder="Name"
                   @if(old('name') !== null) value="{{old('name')}}" @endif
                   dusk="name_input" required
            />
        </x-form.input-wrapper>

        {{--| file upload field |--}}
        <x-form.input-wrapper label_text="Save file csv" cls="large_input mt-2">
            <x-form.input.file_uploader name="csv" required="true" accepts=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"/>
        </x-form.input-wrapper>

        {{--| game selector |--}}
        <x-form.input-wrapper label_text="Game" cls="large_input">
            <div class="flex gap-1 h-8">
                <x-datalist.dataselect.dataselect id="game-selector" name="game" url="{{route('data.pksanc.games.dataselect')}}"
                      item_identifier="game" item_label="name" dynamic_loading="false"/>

                <button type="button" class="interactive font-bold text-2xl" title="add game" onclick="openModal('add_romhack_modal')">+</button>
            </div>
        </x-form.input-wrapper>
    </div>
@stop

@section('modals')
    <x-modal.modal id="add_romhack_modal" confirm_method="saveRomhack()">
        <h3 class="title py-1">Add a romhack</h3>

        <x-form.input-wrapper label_text="Romhack name">
            <input type="text" name="romhack_name" class="mediumInput underlined h-8" placeholder="Name" required>
        </x-form.input-wrapper>

        <x-form.input-wrapper label_text="Original game">
            <select name="romhack_original_game" class="mediumInput underlined py-0">
                <option>Original game</option>
                @foreach ($gamesCollection as $game)
                    @if ($game->original_game === null)
                        <option value="{{$game->game}}">{{$game->name}}</option>
                    @endif
                @endforeach
            </select>
        </x-form.input-wrapper>
    </x-modal.modal>
@stop

@section('submit_route', route('pksanc.deposit.stage.attempt'))
